# Generated by Django 6.0.7 on 2026-07-13 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_city_country_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='closest_big_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='airport.city'),
        ),
    ]
