# Generated by Django 6.0.7 on 2026-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_airport_iata_code_airport_latitude_airport_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
