# Generated by Django 6.0.7 on 2026-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_position_crew_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='flights', to='airport.crew'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='arrival_time_later_than_departure_flight'),
        ),
    ]
