# Generated by Django 6.0.7 on 2026-07-14 23:17

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
