# Generated by Django 6.0.7 on 2026-07-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0009_airplane_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name', 'country'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['source', 'destination']},
        ),
    ]
